language: php
php:
  - 7.1
  - 7.2

install: composer install
script:
  - ./vendor/bin/phpcs --standard=PSR2 src/ tests/
  - ./vendor/bin/phpunit -c phpunit.xml
  - ./vendor/bin/phpstan analyse src --level max