version: "3"

services:
  tale:
    build:
      context: ./
    volumes:
    - "./src:/app/src/"
    - "./tests:/app/tests/"
    - "./composer.json:/app/composer.json"
    - "./infection.json.dist:/app/infection.json.dist"
    - "./logs:/app/logs"
